/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Language } from '../types';

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  ar: {
    // Nav & Common
    dashboard: 'لوحة التحكم',
    pos: 'نظام الكاشير (POS)',
    inventory: 'المخزون والمنتجات',
    spareParts: 'قطع الغيار',
    suppliers: 'الموردون',
    customers: 'العملاء والأقساط',
    maintenance: 'الصيانة والتذاكر',
    settings: 'الإعدادات',
    adminPanel: 'إدارة السيرفر / SaaS',
    telegram: 'تيلغرام المحل',
    logout: 'تسجيل الخروج',
    trial: 'فترة تجريبية',
    active: 'نشط',
    pending: 'قيد الانتظار',
    suspended: 'موقف',
    save: 'حفظ',
    cancel: 'إلغاء',
    delete: 'حذف',
    edit: 'تعديل',
    add: 'إضافة',
    search: 'بحث...',
    actions: 'الإجراءات',
    total: 'الإجمالي',
    status: 'الحالة',
    date: 'التاريخ',
    phone: 'رقم الهاتف',
    email: 'البريد الإلكتروني',
    address: 'العنوان',
    username: 'اسم المستخدم',
    role: 'الصلاحية',
    owner: 'صاحب المحل',
    cashier: 'بائع (كاشير)',
    technician: 'فني صيانة',
    currency: 'العملة',
    language: 'اللغة',
    theme: 'المظهر',
    light: 'مضيء',
    dark: 'ليلي',
    price: 'السعر',
    quantity: 'الكمية',
    quantityMin: 'أدنى حد',
    barcode: 'الكود بار',
    generateBarcode: 'توليد كود بار تلقائي',
    exportBackup: 'تصدير نسخة احتياطية',
    importBackup: 'استيراد نسخة احتياطية',
    print: 'طباعة',
    printBarcodeTag: 'طباعة ملصق السعر',
    printWarranty: 'وصــل الضمـان',
    printReceipt: 'وصــل الـبيـع',
    barcode_or_name: 'امسح الرمز أو أدخل الاسم...',
    no_results: 'لا توجد نتائج مطابقة',

    // POS Specifics
    payment_method: 'طريقة الدفع',
    cash: 'نقدًا (كاش)',
    card: 'بطاقة بنكية',
    installments: 'بالتقسيط / كريدي',
    customer_select: 'اختيار العميل',
    discount: 'الخصم',
    subtotal: 'المجموع الفرعي',
    warranty_period: 'فترة الضمان',
    warranty_none: 'بدون ضمان',
    warranty_3m: '3 أشهر',
    warranty_6m: '6 أشهر',
    warranty_1y: 'سنة واحدة',
    warranty_notes: 'ملاحظات الضمان',
    pay_btn: 'إتمام البيع',
    clear_cart: 'تفريغ السلة',
    price_screen: 'شاشة عرض السعر للمشتري',
    serial_select: 'اختر الرقم التسلسلي (IMEI)',
    imei_required: 'هذا المنتج يتطلب اختيار رقم IMEI للبيع!',
    add_custom_item: 'إضافة بند مخصص للبيع',

    // Inventory
    product_name: 'اسم المنتج',
    brand: 'الماركة',
    type: 'النوع',
    purchase_price: 'سعر الشراء',
    selling_price: 'سعر البيع',
    serial_numbers_list: 'الأرقام التسلسلية (IMEI / SN)',
    imei_comma: 'أدخل الأرقام التسلسلية مفصولة بفاصلة',
    low_stock_warning: 'تنبيه وصول للمستوى الأدنى',
    low_stock_alert: 'المنتجات النافذة أو القريبة من النفاد',
    phone_or_accessory: 'هاتف أو إكسسوار',
    spare_parts_section: 'قسم قطع الغيار',
    part_model: 'الموديل المتوافق',
    supplier_select: 'المورد المشتري منه',
    add_product: 'إضافة منتج جديد',
    add_part: 'إضافة قطعة غيار',
    serial_placeholder: 'أدخل IMEI لتتبع الهواتف والمبيعات',

    // Suppliers & Customers
    phone_accessory_supplier: 'مورد هواتف وإكسسوارات',
    spare_parts_supplier: 'مورد قطع غيار',
    due_amount: 'الكريدي المتبقي للمورد',
    paid_amount: 'المبلغ المدفوع',
    add_supplier: 'إضافة مورد',
    payment_history: 'سجل الدفعات والمستحقات',
    amount_paid: 'المبلغ المسدد الآن',
    notes_placeholder: 'ملاحظات حول الدفعة...',
    add_debt: 'إضافة دفعة من الكريدي',
    customer_installments: 'أقساط العميل وديونه',
    customer_debt: 'إجمالي الديون القائمة',
    personal_docs: 'المعلومات الشخصية والمستندات',
    add_customer: 'إضافة عميل جديد',
    pay_installment: 'دفع قسط عيني',
    remaining_balance: 'المتبقي',

    // Maintenance
    ticket_num: 'رقم التذكرة',
    device_type: 'نوع الجهاز',
    device_model: 'الموديل',
    issue_desc: 'وصف العطل / المشكل',
    tech_progress: 'مراحل الإصلاح وصيانة الأجهزة',
    repair_cost: 'تكلفة الصيانة التقريبية',
    final_repair_cost: 'التكلفة النهائية للقطع + العمل',
    owner_pickup: 'جاهز للاستلام أو تم التسليم',
    add_job: 'فتح تذكرة صيانة جديدة',
    parts_replaced: 'قطع الغيار المستهلكة في الإصلاح',
    labor_cost: 'تكلفة اليد العاملة والجهد',
    inspecting: 'جاري التشخيص وفحص العطل',
    repairing: 'قيد الصيانة واللحام/التغيير',
    ready_for_pickup: 'جاهز للاستلام والتشغيل',
    delivered: 'تم تسليم الجهاز والقبض',
    cancelled: 'ملغى / لم يتم الإصلاح',

    // Settings
    shop_details_logo: 'تفاصيل المحل التجاري والختم والمطبوعات',
    shop_name: 'اسم المحل التجاري',
    shop_phone: 'هاتف المحل الرسمي',
    shop_address: 'العنوان الجغرافي للمحل',
    logo_upload: 'شعار المحل (شكل دائري)',
    stamp_upload: 'ختم وصورة توقيع المحل لفواتير الضمان',
    receipt_custom: 'تخصيص ترويسة وتذييل الفاتورة ووصل الضمان',
    header_text: 'نص الترويسة (Header)',
    footer_text: 'نص التذييل والتعليمات (Footer)',
    theme_styling: 'تغيير الألوان والسمات البصرية',
    sky_blue: 'الأزرق الفاتح والرمادي الهادئ',
    grass_green: 'الأخضر الحشيشي والرمادي الدافئ',
    indigo_dream: 'الأرجواني والأبيض الناصع',
    sound_alerts: 'تنبيهات صوتية ذكية',
    enable_sounds: 'تفعيل الأصوات عند البيع والمسح والتحذير',

    // Admin & SaaS
    admin_title: 'منصة إدارة سيرفر DzStore (للأدمن)',
    total_shops: 'إجمالي المحلات المسجلة',
    awaiting_approval: 'محلات قيد المراجعة والموافقة',
    active_subscriptions: 'الاشتراكات المفعلة والمجانية',
    trial_period: 'التحكم بفترة التجربة والترخيص',
    baridimob_label: 'الدفع في الجزائر: BaridiMob أو كاش',
    trial_days_selector: 'مدة الفترة التجريبية (بالأيام)',
    activate_shop_btn: 'تفعيل حساب المحل',
    suspend_shop_btn: 'تجميد الاشتراك',
    send_broadcast: 'إرسال إشعار تحديث أو رسالة تلقائية',
    broadcast_title: 'عنوان التحديث / الرسالة',
    broadcast_content: 'تفاصيل الإشعار الذي سيظهر لجميع المحلات فورا',
    broadcast_sent_success: 'تم إرسال التحديث بنجاح لجميع أصحاب المحلات!',
    baridimob_details: 'رقم بريدي موب للموزع: RIP: 00799999002345678945 - المفتاح: 42. يرجى إرسال وصل التحويل عبر تيلغرام للأدمن لتفعيل الحساب.',

    // Reg & Authentication
    saas_register_title: 'التسجيل كصاحب محل جديد',
    login_title: 'تسجيل الدخول للمنصة',
    need_account: 'ليس لديك حساب؟ سجل المحل الآن',
    have_account: 'لديك حساب بالفعل؟ دخول',
    admin_mode_notice: 'أنت تدخل كأدمن رئيسي للمنصة',
    shop_unapproved_title: 'حسابك بانتظار التفعيل',
    shop_unapproved_desc: 'لقد سجلت بنجاح! حسابك حالياً قيد المراجعة من قبل الأدمن الرئيسي (gestion.stock34@gmail.com). يرجى إرسال تأكيد الدفع (كاش أو بريدي موب) لتفعيل الحساب بالكامل لتبدأ عملك.',
    contact_admin: 'الاتصال بالدعم والتفعيل عبر تلغرام',
    forgot_password: 'نسيت كلمة المرور؟ استرجاع',
    recovery_code: 'رمز الاسترجاع',
    reset_pass_desc: 'أدخل بريدك الإلكتروني وسيتم تزويدك بالتعليمات فوراً عبر الإيميل أو تواصل مع الأدمن مباشرة.',
  },
  fr: {
    dashboard: 'Tableau de bord',
    pos: 'Point de vente (POS)',
    inventory: 'Inventaire & Produits',
    spareParts: 'Pièces de rechange',
    suppliers: 'Fournisseurs',
    customers: 'Clients & Crédits',
    maintenance: 'Maintenance & Tickets',
    settings: 'Paramètres',
    adminPanel: 'Gestion SaaS / Admin',
    telegram: 'Telegram du Magasin',
    logout: 'Déconnexion',
    trial: 'Période d\'essai',
    active: 'Actif',
    pending: 'En attente',
    suspended: 'Suspendu',
    save: 'Enregistrer',
    cancel: 'Annuler',
    delete: 'Supprimer',
    edit: 'Modifier',
    add: 'Ajouter',
    search: 'Rechercher...',
    actions: 'Actions',
    total: 'Total',
    status: 'Statut',
    date: 'Date',
    phone: 'Téléphone',
    email: 'E-mail',
    address: 'Adresse',
    username: 'Identifiant',
    role: 'Rôle',
    owner: 'Propriétaire',
    cashier: 'Caissier',
    technician: 'Technicien de maintenance',
    currency: 'Devise',
    language: 'Langue',
    theme: 'Thème',
    light: 'Clair',
    dark: 'Sombre',
    price: 'Prix',
    quantity: 'Quantité',
    quantityMin: 'Quantité Min',
    barcode: 'Code-barres',
    generateBarcode: 'Générer un code-barres',
    exportBackup: 'Exporter la sauvegarde',
    importBackup: 'Importer la sauvegarde',
    print: 'Imprimer',
    printBarcodeTag: 'Imprimer étiquette prix',
    printWarranty: 'Ticket de Garantie',
    printReceipt: 'Ticket de Caisse',
    barcode_or_name: 'Numériser ou saisir le nom...',
    no_results: 'Aucun résultat trouvé',

    // POS Specifics
    payment_method: 'Mode de paiement',
    cash: 'Espèces (Cash)',
    card: 'Carte bancaire',
    installments: 'Crédit / Par versements',
    customer_select: 'Sélectionner un client',
    discount: 'Remise',
    subtotal: 'Sous-total',
    warranty_period: 'Période de garantie',
    warranty_none: 'Sans garantie',
    warranty_3m: '3 mois',
    warranty_6m: '6 mois',
    warranty_1y: '1 an',
    warranty_notes: 'Notes de garantie',
    pay_btn: 'Finaliser la vente',
    clear_cart: 'Vider le panier',
    price_screen: 'Écran d\'affichage client',
    serial_select: 'Sélectionner IMEI/SN',
    imei_required: 'Cet article nécessite la sélection d\'un numéro IMEI !',
    add_custom_item: 'Ajouter un article personnalisé',

    // Inventory
    product_name: 'Nom de l\'article',
    brand: 'Marque',
    type: 'Type',
    purchase_price: 'Prix d\'achat',
    selling_price: 'Prix de vente',
    serial_numbers_list: 'Numéros de série (IMEI / SN)',
    imei_comma: 'Saisir les IMEIs séparés par des virgules',
    low_stock_warning: 'Alerte quantité minimale',
    low_stock_alert: 'Articles en rupture ou presque épuisés',
    phone_or_accessory: 'Téléphone ou Accessoire',
    spare_parts_section: 'Pièces de Rechange',
    part_model: 'Modèle compatible',
    supplier_select: 'Fournisseur d\'achat',
    add_product: 'Ajouter un produit',
    add_part: 'Ajouter une pièce de rechange',
    serial_placeholder: 'Entrez l\'IMEI pour suivre les téléphones',

    // Suppliers & Customers
    phone_accessory_supplier: 'Fournisseur Tél & Accessoires',
    spare_parts_supplier: 'Fournisseur Pièces Rechange',
    due_amount: 'Crédit restant dû',
    paid_amount: 'Montant payé',
    add_supplier: 'Ajouter un fournisseur',
    payment_history: 'Historique des paiements',
    amount_paid: 'Montant versé maintenant',
    notes_placeholder: 'Notes sur le versement...',
    add_debt: 'Ajouter au crédit dû',
    customer_installments: 'Crédits & Traites du client',
    customer_debt: 'Total des dettes cumulées',
    personal_docs: 'Dossier & Infos personnelles',
    add_customer: 'Ajouter un client',
    pay_installment: 'Régler un versement',
    remaining_balance: 'Reste',

    // Maintenance
    ticket_num: 'N° Ticket',
    device_type: 'Type d\'appareil',
    device_model: 'Modèle de l\'appareil',
    issue_desc: 'Description de la panne',
    tech_progress: 'Suivi de la réparation',
    repair_cost: 'Coût estimé',
    final_repair_cost: 'Coût total (Pièces + Main d\'œuvre)',
    owner_pickup: 'Prêt pour retrait ou livré',
    add_job: 'Créer un nouveau ticket',
    parts_replaced: 'Pièces de rechange consommées',
    labor_cost: 'Frais de main d\'œuvre',
    inspecting: 'Diagnostic en cours',
    repairing: 'Réparation / Soudure en cours',
    ready_for_pickup: 'Prêt pour retrait',
    delivered: 'Remis et payé',
    cancelled: 'Annulé / Non réparé',

    // Settings
    shop_details_logo: 'Détails du commerce, cachet & imprimés',
    shop_name: 'Nom de la boutique',
    shop_phone: 'Téléphone officiel',
    shop_address: 'Adresse géographique',
    logo_upload: 'Logo de la boutique (Rond)',
    stamp_upload: 'Cachet ou signature pour factures/garanties',
    receipt_custom: 'Entête et pied de ticket personnalisés',
    header_text: 'Texte d\'entête (Header)',
    footer_text: 'Texte de pied de page (Footer)',
    theme_styling: 'Personnaliser l\'apparence',
    sky_blue: 'Bleu ciel et gris épuré',
    grass_green: 'Vert gazon et gris chaleureux',
    indigo_dream: 'Violet royal et blanc épuré',
    sound_alerts: 'Alerte Sonore intelligente',
    enable_sounds: 'Activer le son (Vente, Scanner, Alertes)',

    // Admin & SaaS
    admin_title: 'SaaS Console DzStore (ADMIN)',
    total_shops: 'Magasins inscrits',
    awaiting_approval: 'En attente d\'approbation',
    active_subscriptions: 'Abonnements actifs',
    trial_period: 'Période d\'essai & licences',
    baridimob_label: 'Paiement en Algérie: BaridiMob ou Cash',
    trial_days_selector: 'Durée d\'essai (Jours)',
    activate_shop_btn: 'Activer le magasin',
    suspend_shop_btn: 'Suspendre l\'abonnement',
    send_broadcast: 'Envoyer une note de mise à jour',
    broadcast_title: 'Titre de la note',
    broadcast_content: 'Contenu du message d\'alerte',
    broadcast_sent_success: 'Note diffusée avec succès à tous les magasins !',
    baridimob_details: 'Numéro BaridiMob distributeur: RIP: 00799999002345678945 - Clé: 42. Veuillez envoyer le reçu de virement via Telegram pour activation.',

    // Reg & Authentication
    saas_register_title: 'Inscription de boutique',
    login_title: 'Connexion à l\'application',
    need_account: 'Nouvelle boutique? Inscrivez-vous ici',
    have_account: 'Déjà un compte? Se connecter',
    admin_mode_notice: 'Vous êtes connecté en tant qu\'Administrateur Général',
    shop_unapproved_title: 'Boutique en attente d\'activation',
    shop_unapproved_desc: 'Votre inscription a réussi! Votre compte est actuellement en révision par l\'Administrateur principal (gestion.stock34@gmail.com). Veuillez envoyer votre justificatif de paiement (Cash ou d\'un virement BaridiMob) pour activer l\'accès.',
    contact_admin: 'Contacter le support / Activer via Telegram',
    forgot_password: 'Mot de passe oublié ? Récupérer',
    recovery_code: 'Code de récupération',
    reset_pass_desc: 'Saisissez votre e-mail pour recevoir les instructions ou contactez directement l\'administrateur.',
  },
  en: {
    dashboard: 'Dashboard',
    pos: 'POS Cashier',
    inventory: 'Inventory & Products',
    spareParts: 'Spare Parts',
    suppliers: 'Suppliers',
    customers: 'Customers & Debts',
    maintenance: 'Maintenance & Repairs',
    settings: 'Settings',
    adminPanel: 'SaaS Console / Admin',
    telegram: 'Store Telegram',
    logout: 'Logout',
    trial: 'Trial Period',
    active: 'Active',
    pending: 'Pending',
    suspended: 'Suspended',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    search: 'Search...',
    actions: 'Actions',
    total: 'Total',
    status: 'Status',
    date: 'Date',
    phone: 'Phone',
    email: 'Email',
    address: 'Address',
    username: 'Username',
    role: 'Role',
    owner: 'Store Owner',
    cashier: 'Cashier (Sales)',
    technician: 'Maintenance Tech',
    currency: 'Currency',
    language: 'Language',
    theme: 'Theme',
    light: 'Light',
    dark: 'Dark',
    price: 'Price',
    quantity: 'Quantity',
    quantityMin: 'Min Level',
    barcode: 'Barcode',
    generateBarcode: 'Auto Barcode',
    exportBackup: 'Export Backup',
    importBackup: 'Import Backup',
    print: 'Print',
    printBarcodeTag: 'Print Price Tag',
    printWarranty: 'Print Warranty',
    printReceipt: 'Print Invoice',
    barcode_or_name: 'Scan entry or type name...',
    no_results: 'No results matched',

    // POS Specifics
    payment_method: 'Payment Method',
    cash: 'Cash',
    card: 'Bank Card',
    installments: 'Installments / Credit',
    customer_select: 'Select Customer',
    discount: 'Discount',
    subtotal: 'Subtotal',
    warranty_period: 'Warranty Duration',
    warranty_none: 'No Warranty',
    warranty_3m: '3 Months',
    warranty_6m: '6 Months',
    warranty_1y: '1 Year',
    warranty_notes: 'Warranty Notes',
    pay_btn: 'Finalize Sale',
    clear_cart: 'Clear Cart',
    price_screen: 'Customer Price Display',
    serial_select: 'Select IMEI/SN',
    imei_required: 'This item requires an IMEI code to proceed with selling!',
    add_custom_item: 'Add Custom Item',

    // Inventory
    product_name: 'Product Name',
    brand: 'Brand',
    type: 'Type',
    purchase_price: 'Purchase Price',
    selling_price: 'Selling Price',
    serial_numbers_list: 'Serial Numbers (IMEI / SN)',
    imei_comma: 'Enter multiple IMEIs separated by commas',
    low_stock_warning: 'Minimum threshold alert',
    low_stock_alert: 'Low stock and out-of-stock items',
    phone_or_accessory: 'Device or Accessory',
    spare_parts_section: 'Spare Parts Stock',
    part_model: 'Compatible Model',
    supplier_select: 'Purchased From Supplier',
    add_product: 'Add New Product',
    add_part: 'Add Spare Part',
    serial_placeholder: 'Enter IMEI/SN code to track devices',

    // Suppliers & Customers
    phone_accessory_supplier: 'Phone & Accessory Supplier',
    spare_parts_supplier: 'Spare Parts Supplier',
    due_amount: 'Remaining Supplier Credit',
    paid_amount: 'Amount Paid',
    add_supplier: 'Add Supplier',
    payment_history: 'Payment & Receipt Records',
    amount_paid: 'Amount paid now',
    notes_placeholder: 'Transaction details...',
    add_debt: 'Add to Due Balance',
    customer_installments: 'Customer Installment Plans',
    customer_debt: 'Total Accumulated Debt',
    personal_docs: 'Personal Profile Dossier',
    add_customer: 'Add Customer',
    pay_installment: 'Settle Installment',
    remaining_balance: 'Remaining',

    // Maintenance
    ticket_num: 'Ticket #',
    device_type: 'Device Type',
    device_model: 'Model',
    issue_desc: 'Problem / Failure details',
    tech_progress: 'Maintenance Phases',
    repair_cost: 'Estimated Repair Cost',
    final_repair_cost: 'Final Cost (Parts + Labor)',
    owner_pickup: 'Ready for Pickup or Delivered',
    add_job: 'Open Repair Ticket',
    parts_replaced: 'Consumed Spare Parts',
    labor_cost: 'Labor & Effort Fees',
    inspecting: 'Inspecting / Diagnostic stage',
    repairing: 'In Progress / soldering / changes',
    ready_for_pickup: 'Ready for client pickup',
    delivered: 'Delivered and Settled',
    cancelled: 'Cancelled / Return un-repaired',

    // Settings
    shop_details_logo: 'Commerce settings, digital stamp & layout',
    shop_name: 'Shop Name',
    shop_phone: 'Official Phone',
    shop_address: 'Address location',
    logo_upload: 'Store Logo (circular)',
    stamp_upload: 'Digital Stamp / Signature for receipts',
    receipt_custom: 'Customize receipt headers and instructions',
    header_text: 'Header Instructions',
    footer_text: 'Footer Instructions / Disclaimers',
    theme_styling: 'Color Palette & Themes',
    sky_blue: 'Sky Blue & Light Slate',
    grass_green: 'Grass Green & Soft Slate',
    indigo_dream: 'Royal Purple & Clean White',
    sound_alerts: 'Audio sound alerts',
    enable_sounds: 'Play audio cues on scans, checkouts and notifications',

    // Admin & SaaS
    admin_title: 'DzStore SaaS Admin Gateway',
    total_shops: 'Registered Shops',
    awaiting_approval: 'Awaiting Approvals',
    active_subscriptions: 'Active Subscriptions',
    trial_period: 'Control trial periods and licenses',
    baridimob_label: 'Algerian System: BaridiMob or Cash',
    trial_days_selector: 'Trial Limits (in Days)',
    activate_shop_btn: 'Approve & Activate Account',
    suspend_shop_btn: 'Suspend Shop Access',
    send_broadcast: 'Broadcast instant update notifications',
    broadcast_title: 'Notification Title',
    broadcast_content: 'Details of the automatic broadcast popup',
    broadcast_sent_success: 'Update sent instantly to all shop dashboards!',
    baridimob_details: 'Distributor BaridiMob: RIP: 00799999002345678945 - Key: 42. Send wire snapshot via Telegram channel for instance approval.',

    // Reg & Authentication
    saas_register_title: 'Register New Shop Portal',
    login_title: 'User Login Credentials',
    need_account: 'No account? Register store now',
    have_account: 'Already registered? Login',
    admin_mode_notice: 'Connected as System General Administrator',
    shop_unapproved_title: 'Awaiting Administrator Approval',
    shop_unapproved_desc: 'Registration completed! Your store profile is in the queue to be verified by Chief Admin (gestion.stock34@gmail.com). Send confirmation of your subscription payment (Cash or BaridiMob) to activate features.',
    contact_admin: 'Contact Agent / Settle payment on Telegram',
    forgot_password: 'Forgot password? Recover account',
    recovery_code: 'Security Code',
    reset_pass_desc: 'Settle your registered email and receive instructions immediately or connect directly to administrator.',
  },
  es: {
    dashboard: 'Pulpit nawigacyjny',
    pos: 'Kasa (POS)',
    inventory: 'Magazyn i produkty',
    spareParts: 'Części zamienne',
    suppliers: 'Dostawcy',
    customers: 'Klienci i raty',
    maintenance: 'Zlecenia i naprawy',
    settings: 'Ustawienia',
    adminPanel: 'Zarządzanie serwerem / SaaS',
    telegram: 'Telegram sklepu',
    logout: 'Wyloguj',
    trial: 'Okres próbny',
    active: 'Aktywny',
    pending: 'Oczekujący',
    suspended: 'Zawieszony',
    save: 'Zapisz',
    cancel: 'Anuluj',
    delete: 'Usuń',
    edit: 'Edytuj',
    add: 'Dodaj',
    search: 'Szukaj...',
    actions: 'Operacje',
    total: 'Łącznie',
    status: 'Status',
    date: 'Data',
    phone: 'Telefon',
    email: 'E-mail',
    address: 'Adres',
    username: 'Nazwa użytkownika',
    role: 'Uprawnienia',
    owner: 'Właściciel',
    cashier: 'Sprzedawca (Kasjer)',
    technician: 'Serwisant',
    currency: 'Waluta',
    language: 'Język',
    theme: 'Motyw',
    light: 'Jasny',
    dark: 'Ciemny',
    price: 'Cena',
    quantity: 'Ilość',
    quantityMin: 'Limit min.',
    barcode: 'Kod kreskowy',
    generateBarcode: 'Generuj kod kreskowy',
    exportBackup: 'Eksportuj kopię',
    importBackup: 'Importuj kopię',
    print: 'Drukuj',
    printBarcodeTag: 'Drukuj etykietę ceny',
    printWarranty: 'Drukuj gwarancję',
    printReceipt: 'Drukuj paragon',
    barcode_or_name: 'Zeskanuj kod lub wpisz nazwę...',
    no_results: 'Brak pasujących wyników',

    // POS Specifics
    payment_method: 'Metoda płatności',
    cash: 'Gotówka',
    card: 'Karta bankowa',
    installments: 'Raty / Kredyt',
    customer_select: 'Wybierz klienta',
    discount: 'Rabat',
    subtotal: 'Suma częściowa',
    warranty_period: 'Okres gwarancji',
    warranty_none: 'Brak gwarancji',
    warranty_3m: '3 miesiące',
    warranty_6m: '6 miesięcy',
    warranty_1y: '1 rok',
    warranty_notes: 'Uwagi do gwarancji',
    pay_btn: 'Sfinalizuj sprzedaż',
    clear_cart: 'Wyczyść koszyk',
    price_screen: 'Ekran ceny klienta',
    serial_select: 'Wybierz IMEI/SN',
    imei_required: 'Ten produkt wymaga podania numeru IMEI do sprzedaży!',
    add_custom_item: 'Dodaj własną pozycję',

    // Inventory
    product_name: 'Nazwa produktu',
    brand: 'Marka',
    type: 'Typ',
    purchase_price: 'Cena zakupu',
    selling_price: 'Cena sprzedaży',
    serial_numbers_list: 'Numery seryjne (IMEI / SN)',
    imei_comma: 'Wpisz numery seryjne rozdzielone przecinkami',
    low_stock_warning: 'Ostrzeżenie o stanie minimalnym',
    low_stock_alert: 'Niski stan magazynowy i braki',
    phone_or_accessory: 'Telefon lub Akcesorium',
    spare_parts_section: 'Magazyn części zamiennych',
    part_model: 'Kompatybilny model',
    supplier_select: 'Zakupiono od dostawcy',
    add_product: 'Dodaj produkt',
    add_part: 'Dodaj część zamienną',
    serial_placeholder: 'Wpisz kod IMEI/SN, aby śledzić urządzenia',

    // Suppliers & Customers
    phone_accessory_supplier: 'Dostawca telefonów i akcesoriów',
    spare_parts_supplier: 'Dostawca części zamiennych',
    due_amount: 'Pozostałe saldo należności',
    paid_amount: 'Kwota zapłacona',
    add_supplier: 'Dodaj dostawcę',
    payment_history: 'Historia płatności',
    amount_paid: 'Kwota wpłacona teraz',
    notes_placeholder: 'Szczegóły płatności...',
    add_debt: 'Dodaj do salda należności',
    customer_installments: 'Raty i długi klienta',
    customer_debt: 'Suma zadłużenia',
    personal_docs: 'Dane osobowe i dokumenty',
    add_customer: 'Dodaj klienta',
    pay_installment: 'Spłać ratę',
    remaining_balance: 'Pozostało',

    // Maintenance
    ticket_num: 'Zgłoszenie #',
    device_type: 'Typ urządzenia',
    device_model: 'Model',
    issue_desc: 'Opis usterki / problemu',
    tech_progress: 'Etap naprawy',
    repair_cost: 'Szacowany koszt naprawy',
    final_repair_cost: 'Ostateczny koszt (części + robocizna)',
    owner_pickup: 'Gotowe do odbioru / wydane',
    add_job: 'Otwórz nowe zlecenie',
    parts_replaced: 'Zużyte części zamienne',
    labor_cost: 'Koszt robocizny',
    inspecting: 'Diagnostyka w toku',
    repairing: 'W trakcie naprawy / lutowania',
    ready_for_pickup: 'Gotowe do odbioru',
    delivered: 'Wydano i opłacono',
    cancelled: 'Anulowano / Zwrot bez naprawy',

    // Settings
    shop_details_logo: 'Ustawienia firmy, pieczęć i wydruki',
    shop_name: 'Nazwa sklepu',
    shop_phone: 'Oficjalny telefon',
    shop_address: 'Adres sklepu',
    logo_upload: 'Logo sklepu (okrągłe)',
    stamp_upload: 'Pieczęć cyfrowa / podpis do gwarancji',
    receipt_custom: 'Dostosuj nagłówek i stopkę wydruku',
    header_text: 'Instrukcje w nagłówku',
    footer_text: 'Instrukcje w stopce / wyłączenia',
    theme_styling: 'Paleta kolorów i style',
    sky_blue: 'Błękit nieba i jasny szary',
    grass_green: 'Zieleń trawy i ciepły szary',
    indigo_dream: 'Królewski fiolet i czysta biel',
    sound_alerts: 'Inteligentne powiadomienia dźwiękowe',
    enable_sounds: 'Włącz dźwięki przy sprzedaży, skanowaniu i powiadomieniach',

    // Admin & SaaS
    admin_title: 'SaaS Platforma Zarządzania DzStore (ADMIN)',
    total_shops: 'Zarejestrowane sklepy',
    awaiting_approval: 'Sklepy oczekujące na weryfikację',
    active_subscriptions: 'Aktywne subskrypcje',
    trial_period: 'Okresy próbne i licencje',
    baridimob_label: 'System algierski: BaridiMob lub gotówka',
    trial_days_selector: 'Okres próbny (w dniach)',
    activate_shop_btn: 'Aktywuj i zatwierdź konto',
    suspend_shop_btn: 'Zawieś subskrypcję',
    send_broadcast: 'Prześlij komunikat do wszystkich',
    broadcast_title: 'Tytuł komunikatu',
    broadcast_content: 'Szczegóły automatycznego powiadomienia',
    broadcast_sent_success: 'Krótki komunikat rozesłany pomyślnie!',
    baridimob_details: 'Dystrybutor BaridiMob: RIP: 00799999002345678945 - Numer: 42. Wyślij potwierdzenie przelewu na Telegram, aby aktywować.',

    // Reg & Authentication
    saas_register_title: 'Zarejestruj nowy serwis sklepu',
    login_title: 'Logowanie użytkownika',
    need_account: 'Nie masz konta? Zarejestruj się teraz',
    have_account: 'Masz już konto? Zaloguj się',
    admin_mode_notice: 'Zalogowano jako Główny Administrator Systemu',
    shop_unapproved_title: 'Oczekiwanie na zatwierdzenie',
    shop_unapproved_desc: 'Rejestracja zakończona sukcesem! Profil Twojego sklepu czeka na weryfikację przez głównego administratora (gestion.stock34@gmail.com). Wyślij potwierdzenie subskrypcji (gotówka lub przelew), aby aktywować funkcje.',
    contact_admin: 'Wsparcie i aktywacja / Połącz przez Telegram',
    forgot_password: 'Zapomniałeś hasła? Odzyskaj konto',
    recovery_code: 'Kod zabezpieczający',
    reset_pass_desc: 'Podaj swój adres e-mail, aby natychmiast otrzymać instrukcje lub skontaktuj się z administratorem.',
  },
};

export const INITIAL_PRODUCTS = [];

export const INITIAL_SPARE_PARTS = [];

export const INITIAL_SUPPLIERS = [];

export const INITIAL_CUSTOMERS = [];

export const INITIAL_MAINTENANCE_JOBS = [];

export const INITIAL_SHOPS = [
  {
    id: 'system-admin-tenant',
    name: 'سيرفر الإدارة العامة (DzStore SaaS)',
    ownerEmail: 'gestion.stock34@gmail.com',
    phone: '0656000000',
    address: 'الجزائر العاصمة',
    status: 'active' as const,
    trialEndDate: '2029-12-31',
    createdAt: '2026-04-01',
    updatedAt: '2026-04-01',
    subscriptionPlan: 'yearly' as const,
  }
];

export const BROADCAST_MESSAGES = [
  {
    id: 'b-1',
    title: 'مرحباً في نظام DzStore الرسمي 🚀',
    content: 'تم تفعيل النسخة الرسمية الحائزة على التراخيص الكاملة وتتبع المبيعات والمخزن والصيانة.',
    date: '2026-06-06',
    isUpdate: true,
  }
];
